# Site-wide generic info (overridable per-page)
title: Known Issues
description: Nathaniel Warburton's tech website.
author: Nathaniel Warburton
theme-color: "#430f7b"
image:

# Site-wide hardcoded (non-overridable by pages)
url: storyaddict.github.io/known-issues-blog/
# baseurl: /
made-in: Colorado
birthday: '1992-01-25'

# Site-wide social info
donate: 
email: nathanielwarburton@protonmail.com
github_user: storyaddict # user with no @
gitlab_user: storyaddict # user with no @
pixelfed: "https://pixelfed.social/i/web/profile/91616240531017728" # whole URL since it's federated
mastodon: "https://mastodon.social/@warburtonstoryaddict" # whole URL since it's federated
steam: turbwroan # user/alias, no @
twitch: turbwroan

# Settings
permalink: /blog/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

collections:
  products:
    output: true
    permalink: /store/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
